function params=readParameters(species,parameters)

% species = 'Mouse';
% parameters = 'Mouse.parameters.xml';

params = struct('rnaSeq','',...
    'cdna','','ncrna','',...
    'abundantrna','',...
    'transcriptList','',...
    'OligoArray','',...
    'oligos','');

tree = xmlread(parameters);
parameters=xmlParse(tree, 'tree', 'parameters');

general=xmlParse(parameters, 'parameters', 'general');
rnaSeq=xmlParse(parameters, 'parameters', 'rnaSeq');
cdna=xmlParse(parameters, 'parameters', 'cdna');
ncrna=xmlParse(parameters, 'parameters', 'ncrna');
abundantrna=xmlParse(parameters, 'parameters', 'abundantrna');
transcriptList=xmlParse(parameters, 'parameters', 'transcriptList');
OligoArray=xmlParse(parameters, 'parameters', 'OligoArray');
oligos=xmlParse(parameters, 'parameters', 'oligos');
adapters=xmlParse(parameters, 'parameters', 'adapters');
onePCR=xmlParse(parameters, 'parameters', 'onePCR');

%% Parse general parameters
verbose=xmlParse(general, 'general', 'verbose');

%% Parse parameters for rnaSeq
data=xmlParse(rnaSeq, 'rnaSeq', 'data');
if str2double(data.getFirstChild.getData)==0
    dir1=data;
    dir2=data;
elseif str2double(data.getFirstChild.getData)==1
    dir1=xmlParse(rnaSeq, 'rnaSeq', 'dir1');
    dir2=dir1;
elseif str2double(data.getFirstChild.getData)==2
    dir1=xmlParse(rnaSeq, 'rnaSeq', 'dir1');
    dir2=xmlParse(rnaSeq, 'rnaSeq', 'dir2');
end
mRNA=xmlParse(rnaSeq, 'rnaSeq', 'mRNA');
key1=xmlParse(rnaSeq, 'rnaSeq', 'key1');
key2=xmlParse(rnaSeq, 'rnaSeq', 'key2');
thres=xmlParse(rnaSeq, 'rnaSeq', 'thres');

params.rnaSeq = struct('species',species,...
    'verbose',str2double(verbose.getFirstChild.getData),...
    'data',str2double(data.getFirstChild.getData),...
    'dir1',char(dir1.getFirstChild.getData),...
    'dir2',char(dir2.getFirstChild.getData),...
    'mRNA',str2double(mRNA.getFirstChild.getData),...
    'keys',{char(key1.getFirstChild.getData),char(key2.getFirstChild.getData)},...
    'thres',str2double(thres.getFirstChild.getData));

%% Parse parameters for cdna
dir1=xmlParse(cdna, 'cdna', 'dir1');
key1=xmlParse(cdna, 'cdna', 'key1');
key2=xmlParse(cdna, 'cdna', 'key2');

params.cdna = struct('species',species,...
    'verbose',str2double(verbose.getFirstChild.getData),...
    'dir1',char(dir1.getFirstChild.getData),...
    'keys',{char(key1.getFirstChild.getData),char(key2.getFirstChild.getData)});

%% Parse parameters for ncrna
dir1=xmlParse(ncrna, 'ncrna', 'dir1');
tRNA=xmlParse(ncrna, 'ncrna', 'tRNA');
if str2double(tRNA.getFirstChild.getData)==1
    dirT=xmlParse(ncrna, 'ncrna', 'dirT');
else
    dirT=tRNA;
end
key1=xmlParse(ncrna, 'ncrna', 'key1');
key2=xmlParse(ncrna, 'ncrna', 'key2');
key3=xmlParse(ncrna, 'ncrna', 'key3');

params.ncrna = struct('species',species,...
    'verbose',str2double(verbose.getFirstChild.getData),...
    'dir1',char(dir1.getFirstChild.getData),...
    'tRNA',str2double(tRNA.getFirstChild.getData),...
    'dirT',char(dirT.getFirstChild.getData),...
    'keys',{char(key1.getFirstChild.getData),char(key2.getFirstChild.getData),...
    char(key3.getFirstChild.getData)});

%% Parse parameters for abundantrna
percent=xmlParse(abundantrna, 'abundantrna', 'percent');
key1=xmlParse(abundantrna, 'abundantrna', 'key1');
key2=xmlParse(abundantrna, 'abundantrna', 'key2');
key3=xmlParse(abundantrna, 'abundantrna', 'key3');
key4=xmlParse(abundantrna, 'abundantrna', 'key4');
key5=xmlParse(abundantrna, 'abundantrna', 'key5');

params.abundantrna = struct('species',species,...
    'verbose',str2double(verbose.getFirstChild.getData),...
    'percent',str2double(percent.getFirstChild.getData),...
    'keys',{char(key1.getFirstChild.getData),char(key2.getFirstChild.getData),...
    char(key3.getFirstChild.getData),char(key4.getFirstChild.getData),...
    char(key5.getFirstChild.getData)});

%% Parse parameters for transcriptList
dir1=xmlParse(transcriptList, 'transcriptList', 'dir1');
len=xmlParse(transcriptList, 'transcriptList', 'length');
num=xmlParse(transcriptList, 'transcriptList', 'number');

params.transcriptList = struct('species',species,...
    'verbose',str2double(verbose.getFirstChild.getData),...
    'dir1',char(dir1.getFirstChild.getData),...
    'length',str2double(len.getFirstChild.getData),...
    'number',str2double(num.getFirstChild.getData));

%% Parse parameters for OligoArray


%% Parse parameters for oligos
key1=xmlParse(oligos, 'oligos', 'key1');
key2=xmlParse(oligos, 'oligos', 'key2');
num=xmlParse(oligos, 'oligos', 'number');
seqNum=xmlParse(oligos, 'oligos', 'seqNum');
thres=xmlParse(oligos, 'oligos', 'thres');
querySize=xmlParse(oligos, 'oligos', 'querySize');
DbSize=xmlParse(oligos, 'oligos', 'DbSize');
blastArgs=xmlParse(oligos, 'oligos', 'blastArgs');
parallel=xmlParse(oligos, 'oligos', 'parallel');
dir1=xmlParse(oligos, 'oligos', 'dir1');

params.oligos = struct('species',species,...
    'verbose',str2double(verbose.getFirstChild.getData),...
    'keys',{char(key1.getFirstChild.getData),char(key2.getFirstChild.getData)},...
    'number',str2double(num.getFirstChild.getData),...
    'seqNum',str2double(seqNum.getFirstChild.getData),...
    'thres',str2double(thres.getFirstChild.getData),...
    'querySize',str2double(querySize.getFirstChild.getData),...
    'DbSize',str2double(DbSize.getFirstChild.getData),...
    'blastArgs',char(blastArgs.getFirstChild.getData),...
    'parallel',str2double(parallel.getFirstChild.getData),...
    'specialTranscripts',char(dir1.getFirstChild.getData));

%% Parse parameters for adapters
dir1=xmlParse(adapters, 'adapters', 'dir1');
key1=xmlParse(adapters, 'adapters', 'key1');
gf=xmlParse(adapters, 'adapters', 'gf');
grr=xmlParse(adapters, 'adapters', 'grr');
T7r=xmlParse(adapters, 'adapters', 'T7r');
rRr=xmlParse(adapters, 'adapters', 'rRr');
rGr=xmlParse(adapters, 'adapters', 'rGr');
rBr=xmlParse(adapters, 'adapters', 'rBr');
rIRr=xmlParse(adapters, 'adapters', 'rIRr');

params.adapters = struct('species',species,...
    'verbose',str2double(verbose.getFirstChild.getData),...
    'dir1',char(dir1.getFirstChild.getData),...
    'keys',char(key1.getFirstChild.getData),...
    'gf',char(gf.getFirstChild.getData),...
    'grr',char(grr.getFirstChild.getData),...
    'T7r',char(T7r.getFirstChild.getData),...
    'rRr',char(rRr.getFirstChild.getData),...
    'rGr',char(rGr.getFirstChild.getData),...
    'rBr',char(rBr.getFirstChild.getData),...
    'rIRr',char(rIRr.getFirstChild.getData));

%% Parse parameters for 1stPCR
key1=xmlParse(onePCR, 'onePCR', 'key1');
seqNum=xmlParse(onePCR, 'onePCR', 'seqNum');
thres=xmlParse(onePCR, 'onePCR', 'thres');
querySize=xmlParse(onePCR, 'onePCR', 'querySize');
blastArgs=xmlParse(onePCR, 'onePCR', 'blastArgs');
parallel=xmlParse(onePCR, 'onePCR', 'parallel');
gf=xmlParse(onePCR, 'onePCR', 'gf');
grr=xmlParse(onePCR, 'onePCR', 'grr');

params.onePCR = struct('species',species,...
    'verbose',str2double(verbose.getFirstChild.getData),...
    'keys',char(key1.getFirstChild.getData),...
    'seqNum',str2double(seqNum.getFirstChild.getData),...
    'thres',str2double(thres.getFirstChild.getData),...
    'querySize',str2double(querySize.getFirstChild.getData),...
    'blastArgs',char(blastArgs.getFirstChild.getData),...
    'parallel',str2double(parallel.getFirstChild.getData),...
    'gf',char(gf.getFirstChild.getData),...
    'grr',char(grr.getFirstChild.getData));

